<?php
	/**
	 * Implements hook_help().
	 */
	function events_manager_help($route_name) {
		switch ($route_name) {
			case 'help.page.events_manager':
				return t('Custom module for managing events.');
		}
	}

	/**
	 * Implements hook_theme().
	 */
	function events_manager_theme($existing, $type, $theme, $path) {
		return [
			'events_manager_event_list' => [
				'variables' => [
					'events' => [],
					'add_event_url' => NULL,
					'pager' => [
						'#type' => 'pager',
					]
				],
				'template' => 'events-manager-event-list',
			],
		];
	}
